apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-observability
  namespace: techinea
  labels:
    app: aiops-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-observability
  template:
    metadata:
      labels:
        app: aiops-observability
    spec:
      containers:
      - name: aiops-main
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8050
          name: dashboard
        env:
        - name: KUBERNETES_CONTEXT
          value: "{{ .Values.kubernetes.context }}"
        - name: PROMETHEUS_URL
          value: "{{ .Values.prometheus.url }}"
        - name: NAMESPACE
          value: "techinea"
        resources:
          requests:
            cpu: 512m
            memory: 512Mi
          limits:
            cpu: 1024m
            memory: 2Gi
      serviceAccountName: aiops-observability-sa