apiVersion: v1
kind: Service
metadata:
  name: aiops-observability-service
  namespace: techinea
  labels:
    app: aiops-observability
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8050
    name: http
  selector:
    app: aiops-observability